check:
  - thoth-build
  - thoth-precommit
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.35.1
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: build-watcher
  registry-secret: thoth-station-thoth-pusher-secret
